language: csharp
mono: none
dotnet: 5.0.102
solution: Orca.sln
script:
  - dotnet restore 
  - dotnet build
  - dotnet test
services:
  - mysql
before_install:
  - mysql -u root --password="" < Orca/Database/OrcaDatabase.sql 
